- name: "Creates directory"
  become: yes
  file:
    path: "/srv/stg"
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "/home/circleci/source/artifact-backend.tar.gz"
    dest: "/srv/stg"

# - name: "Extract backend"
#   unarchive:
#     remote_src: yes
#     src: "~/server/artifact-backend.tar.gz"
#     dest: "~/server"

# - name: "Run the web server"
#   shell:
#     cmd: |
#       cd ~/server
#       npm install
#       pm2 stop default
#       pm2 start npm -- start --wait-ready