# Use the latest version of CircleCI's 2.1 YAML
version: 2.1

# Define a job called "hello-world"
jobs:
  # hello-world:
  #   # Use the official CircleCI Docker image
  #   docker:
  #     - image: cimg/base:stable
  #   # Specify the steps that will run as part of the job
  #   steps:
  #     # Checkout the code from the Git repository
  #     - checkout
  #     # Run a command to print "Hello, World!"
  #     - run: echo "Hello, World!
  
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            exit 1
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build  
  
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test-frontend
          command: | 
            cd frontend
            npm install
            npm audit fix --force
            npm run test
workflows:
  version: 2
  udacity-project-3:
    jobs:

      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
