# Use the latest version of CircleCI's 2.1 YAML
version: 2.1

# Define a job called "hello-world"
jobs:
  hello-world:
    # Use the official CircleCI Docker image
    docker:
      - image: cimg/base:stable
    # Specify the steps that will run as part of the job
    steps:
      # Checkout the code from the Git repository
      - checkout
      # Run a command to print "Hello, World!"
      - run: echo "Hello, World! 2"

# Define a workflow that will run the "hello-world" job
workflows:
  version: 2
  hello-world:
    jobs:
      - hello-world
