# Use the latest version of CircleCI's 2.1 YAML
version: 2.1
# commands:
#   destroy-environment:
#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
#     parameters:
#       WorkflowID:
#         Description: The ID of the workflow.
#         Default: udapeople-kk1j287dhjppmz437      
#     steps:
#       - run:
#           name: Destroy environments
#           when: on_fail
#           command: |
#             aws cloudformation delete-stack --stack-name backend-stack
#             aws cloudformation delete-stack --stack-name frontend-stack


jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install  
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build  
  
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test-frontend
          command: |
            curl icanhazip.com 
            cd frontend
            npm install
            npm run test

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: test-backend
          command: | 
            curl icanhazip.com
            cd backend
            npm install
            npm run test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: scan-backend
          command: | 
            cd backend
            npm install   
            npm audit fix --audit-level=critical --force        
            npm audit --audit-level=critical


  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: scan-backend
          command: | 
            cd backend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical       

  # deploy-infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     # Checkout code from git
  #     - checkout
  #     - run:
  #         name: Ensure back-end infrastructure exists
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file .circleci/files/backend.yml \
  #             --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
  #             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
  #             --tags project=udapeople 
  #     - run:
  #         name: Ensure front-end infrastructure exist
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file .circleci/files/frontend.yml \
  #             --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
  #             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
  #             --tags project=udapeople  
      
  #     - run: 
  #         name: install gzip
  #         command:
  #           #yum install tar -y
  #           #yum install gzip -y
  #     - persist_to_workspace:
  #         root: ~/
  #         paths:
  #           - project/.circleci/ansible/inventory.txt
  #     #
  #     # Here's where you will add some code to rollback on failure  

  configure-infrastructure:
    docker:
      - image: circleci/python:3.9
    steps:
      # Checkout code from git
      # Add ssh keys with fingerprint
      # attach workspace
      checkout
      - run:
          name: Install dependencies
          command: |
            echo "Install step"
      - run:
          name: Configure server
          command: |
            echo "config step"
      # Here's where you will add some code to rollback on failure      

workflows:
  version: 2
  udacity-project-3:
    jobs:

      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend: 
          requires: [build-backend]
      #- scan-frontend:
      #    requires: [build-frontend]
      #- scan-backend:
      #    requires: [build-backend]
      # - deploy-infrastructure:
      #     requires: [test-frontend, test-backend]
      #     filters:
      #       branches:
      #         only: [master]